spring:
  application:
    name: solaria-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        formatSql: true
        useSqlComments: true
server:
  port: 8080
  servlet:
    context-path: /solaria/api